site_name:        Splines.jl
repo_url:         http://github.com/byuflowlab/Splines.jl
site_description: Splines Package
site_author:      juddmehr

theme: cinder

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

nav:
  - Home: 'src/index.md'
  - About:
    - 'License': 'src/license.md'